### ISSUE TITLE
添加依赖列表

### ISSUE THREAD

**Issue by Wenti-D** [NanFangXiJi/FaceRecognitionOnFacenetPytorch#1]
建议添加 `requirements.txt` 以标明项目依赖的包，而不是让大伙猜依赖。

~~太强了，北方~~

**Comment by NanFangXiJi** [comment]
# Done

`requirements.txt` has been added.
###### nnd

**Comment by Wenti-D** [comment]
好！但是其实你修了的话就可以自己把这个关了的。

~~太强了，东西南北中发白方~~
